### ISSUE TITLE
Config.cs file needs to be added

### ISSUE THREAD

**Issue by ilkayilknur** [daronyondem/xogo#1]
[xogoMobile.projitems](https://github.com/daronyondem/xogo/blob/master/xogoMobile/xogoMobile/xogoMobile.projitems#L16) has reference to Config.cs file but it looks like config.cs file is missing in project folder.
![image](https://cloud.githubusercontent.com/assets/5785927/7896529/156bb08e-06c6-11e5-94de-22dc5c45ee0c.png)

**Comment by daronyondem** [comment]
Yes, it is missing in purpose. You need to copy config.cs.example, fill in your values.
